name: Test

on:
    push:
      branches: [ master ]
    pull_request:

permissions: read-all

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"

      - name: Check formatting
        run: scarb fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"

      - name: Run tests
        run: scarb test
